apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
 replicas: 4
 selector:
    app: myjavaapp
 template: 
    metadata:
     labels:
      app: myjavaapp
    spec:
     containers:
      - name: myjavaapp-container
        image: revraj03/myjavaapp
        ports: 
        - containerPort: 8080
  