apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
     app: myjavaapp
spec:
  type: NodePort
  ports:
  - port: 8080
    Nodeport: 30001
    protocol: TCP
  selector:
    app: myjavaapp